import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]
live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
opacity = 0.93
dynamic_padding = true
title="nick"
decorations="None"
# startup_mode="Fullscreen"
padding = {x = 5, y = 5}

[shell]
program = "zsh"

[font]
size = 14.0
offset.y = 2

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Heavy"

[font.bold_italic]

family = "JetBrainsMonoNL Nerd Font"
style = "Heavy Italic"

[font.italic]

family = "JetBrainsMonoNL Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"
