# import = [
#     "~/.config/alacritty/themes/themes/gruvbox_material.toml"
# ]
live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
opacity = 0.9
dynamic_padding = true
title="nick"
decorations="None"
# startup_mode="Fullscreen"
padding = {x = 3, y = 5}

[shell]
program = "zsh"

[font]
offset.y = 2
size = 15.0

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.bold_italic]

family = "Hurmit Nerd Font"
style = "Bold Italic"

[font.italic]

family = "Hurmit Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

